define package/playbot/configure
    PKG_SOURCE_DIR:=$(SRC_TOP_DIR)/playbot
    PKG_VERSION:=1.0
    PKG_DEPENDS:=libfirmware libcanopen libbot libdriver
endef

$(eval $(call DefineFirmware,playbot))
