define package/playbot-simulator/configure
    PKG_SOURCE_DIR:=$(SRC_TOP_DIR)/playbot-simulator
    PKG_VERSION:=1.0
    PKG_DEPENDS:=libfirmware libbot libcanopen
endef

$(eval $(call DefineFirmware,playbot-simulator))
